const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
global.crypto = require('node:crypto').webcrypto;
global.fflate = require(path.join(root, 'docs/assets/fflate-0.8.3.js'));
global.window = {};
global.document = {querySelectorAll: () => []};
vm.runInThisContext(fs.readFileSync(path.join(root, 'docs/assets/source-import.js'), 'utf8'));
const hash = s => require('node:crypto').createHash('sha256').update(s).digest('hex');
const text = '\ufeffclass Café {\n  String x = "<script>not executable</script>";\n}\n';
const manifest = {dataset:'buse', revision:'test', samples:[{task_id:'Buse/1',sha256:hash(text)},{task_id:'Buse/2',sha256:hash(text)}]};
(async () => {
  const zip = fflate.zipSync({'nested/irrelevant-name.jsnp':fflate.strToU8(text.replace(/\n/g,'\r\n')), 'ignore.txt':fflate.strToU8('not source')});
  const parsed = await window.BTTFSourceImport.parseArchive(zip, manifest);
  assert.equal(parsed.sources['Buse/1'], text);
  assert.equal(parsed.sources['Buse/2'], text);
  const folderFile = {name:'unrelated-name.jsnp',size:Buffer.byteLength(text),arrayBuffer:async()=>fflate.strToU8(text.replace(/\n/g,'\r\n'))};
  const folder = await window.BTTFSourceImport.parseFolder([folderFile], manifest);
  assert.deepEqual(folder, parsed);
  await assert.rejects(() => window.BTTFSourceImport.parseFolder([],manifest), /Matched 0\/2/);
  await assert.rejects(() => window.BTTFSourceImport.parseFolder([{...folderFile,size:2*1024*1024+1}],manifest), /too large/);
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(zip, {...manifest,dataset:'dorn'}), /Matched 0\/2/);
  const dornText = text.replace(/\n/g, '\r\n');
  const dorn = await window.BTTFSourceImport.parseArchive(zip,{dataset:'dorn',revision:'test',samples:[{task_id:'Dorn/java/1',sha256:hash(dornText)}]});
  assert.equal(dorn.sources['Dorn/java/1'], dornText);
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(fflate.zipSync({'1.jsnp':fflate.strToU8('wrong source')}),manifest), /Matched 0\/2/);
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(new Uint8Array(10*1024*1024+1), manifest), /maximum 10 MB/);
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(fflate.zipSync({'1.jsnp':new Uint8Array(2*1024*1024+1)}), manifest), /too large/);
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(fflate.zipSync({'1.jsnp':new Uint8Array([255,255])}), manifest));
  await assert.rejects(() => window.BTTFSourceImport.parseArchive(new Uint8Array([1,2,3]), manifest));
  console.log('Browser ZIP parser: matching, newline policy, Unicode/BOM, duplicate hashes, mismatches, malformed/oversized archives passed.');
})().catch(error => {console.error(error);process.exitCode=1;});
