"""Label-blind cross-language fixtures for deterministic comment mechanisms."""

import inspect
import math
from types import SimpleNamespace

import numpy as np
import pytest

from experiments.supplementary.comment_validity.comment_content_groups import (
    GROUPS,
    PREFIX,
    aggregate_content_groups,
    classify_comment_content,
)
from src.methods.readability_model.llm_features.types import TokenLoss


@pytest.mark.parametrize("text,language,syntax_form", [
    ("// int count = 3;", "java", "line"),
    ("// values.sort();", "java", "line"),
    ('// logger.info("Continue with processing after validation.");', "java", "line"),
    ('// logger.info("Warning: // validate the input first");', "java", "line"),
    ("/* return count + 1; */", "java", "block"),
    ("// std::cout << value << std::endl;", "cpp", "line"),
    ("// std::vector<int> values;", "cpp", "line"),
    ("// #include <vector>", "cpp", "line"),
    ("// *ptr = 1;", "cpp", "line"),
    ('// const char* notice = "Copyright Example Contributors";', "cpp", "line"),
    ('// std::cout << "Warning: // validate the input first";', "cpp", "line"),
    ("# count = count + 1", "python", "line"),
    ("# import os", "python", "line"),
    ("# return count + 1", "python", "line"),
    ('# print("Continue with processing after validation.")', "python", "line"),
    ('# print("Warning: # validate the input first")', "python", "line"),
])
def test_complete_standalone_commented_code_is_code_like(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "code_like", classified


@pytest.mark.parametrize("text,language,syntax_form", [
    ("// Sort the values; return the smallest element.", "java", "line"),
    ("// Free the buffer; it is no longer needed.", "cpp", "line"),
    ("# Return the result after validating the input.", "python", "line"),
    ('"""Compute and return the sum of the values."""', "python", "documentation"),
    ('r"""Return the normalized path for the requested file."""', "python", "documentation"),
    ("/**\n * @param values the input values to sort\n */", "java", "documentation"),
    ("/**\n * @return the smallest value in the input list\n */", "java", "documentation"),
    ("// TODO: improve the error handling for missing files.", "cpp", "line"),
    ("// Look up the result in <code>Map</code> before computing it.", "java", "line"),
    ("# Store the result in `cache` for later requests.", "python", "line"),
    ("// Check the license before redistributing the package.", "cpp", "line"),
])
def test_explanation_is_prose_not_semicolon_code_or_annotation_metadata(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "prose", classified


@pytest.mark.parametrize("text,language,syntax_form", [
    ("// Copyright (c) 2024 Example Contributors", "java", "line"),
    ("/* Licensed under the Apache License, Version 2.0. */", "cpp", "block"),
    ("# Generated by protoc. DO NOT EDIT.", "python", "line"),
    ("// Source: https://example.org/reference", "cpp", "line"),
    ("/** @author Alice */", "java", "documentation"),
])
def test_explicit_license_or_provenance_is_metadata(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "metadata", classified


@pytest.mark.parametrize("text,language,syntax_form", [
    ("// =======================================", "java", "line"),
    ("# ---------------------------------------", "python", "line"),
    ("/* *********************** */", "cpp", "block"),
    ("// ─────────────────────────", "cpp", "line"),
])
def test_punctuation_only_separators_are_not_code_or_prose(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "separator", classified


@pytest.mark.parametrize("text,language,syntax_form", [
    ("/*\nint count = 3;\nInitialize the count before entering the loop.\n*/", "java", "block"),
    ("/*\nstd::cout << value;\nPrint the current value for debugging.\n*/", "cpp", "block"),
    ('"""\ncount = count + 1\nIncrement the count after validating the input.\n"""', "python", "documentation"),
    ("// Execute `count += 1;` after validating the input.", "cpp", "line"),
    ("// values.sort(); // Sort the values before returning.", "java", "line"),
    ("// *ptr = 1; // Reset the buffer before returning.", "cpp", "line"),
    ("# count += 1 # Increment after validating the input.", "python", "line"),
])
def test_code_plus_explanation_is_not_forced_into_a_pure_group(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "mixed_unknown", classified


@pytest.mark.parametrize("text,language,syntax_form", [
    ("// count", "java", "line"),
    ("// alpha_beta", "cpp", "line"),
    ("# count", "python", "line"),
    ("// count;", "cpp", "line"),
    ("// 42", "java", "line"),
    ("// error???", "cpp", "line"),
    ("//", "java", "line"),
    ("#", "python", "line"),
    ("/** */", "java", "documentation"),
])
def test_empty_or_bare_identifiers_have_insufficient_semantic_signal(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "unknown", classified


def test_delimiters_and_decorative_prefixes_are_removed_but_pointer_operator_is_not():
    documentation = classify_comment_content(
        "/**\n * @param values the input values to sort\n */", "java", "documentation"
    )
    assert documentation.body == "@param values the input values to sort"
    pointer = classify_comment_content("/* *ptr = 1; */", "cpp", "block")
    assert pointer.body == "*ptr = 1;"
    assert pointer.group == "code_like"


def test_url_is_not_truncated_as_an_inline_comment_delimiter():
    text = "// Source: https://example.org/reference"
    classified = classify_comment_content(text, "cpp", "line")
    assert classified.body == "Source: https://example.org/reference"
    assert classified.group == "metadata"


def test_classifier_contract_is_deterministic_and_has_no_label_inputs():
    assert set(GROUPS) == {
        "code_like", "separator", "metadata", "prose", "mixed_unknown", "unknown"
    }
    assert set(inspect.signature(classify_comment_content).parameters) == {
        "text", "language", "syntax_form"
    }
    fixtures = [
        ("// int count = 3;", "java", "line"),
        ("# Return the smallest value in the input list.", "python", "line"),
        ("// count", "cpp", "line"),
    ]
    for args in fixtures:
        first = classify_comment_content(*args)
        assert first.group in GROUPS
        assert isinstance(first.reason, str) and first.reason.strip()
        assert isinstance(first.body, str)
        for _ in range(10):
            repeated = classify_comment_content(*args)
            assert (repeated.group, repeated.reason, repeated.body) == (
                first.group, first.reason, first.body
            )


def test_aggregation_partitions_original_loss_and_bytes_not_normalized_bodies():
    source = "π = 1;\n// Compute the sum for α.\n// -------\nint x = 0;\n// count"
    raw_comments = ["// Compute the sum for α.", "// -------", "// count"]
    spans = [SimpleNamespace(start=source.index(raw), end=source.index(raw) + len(raw))
             for raw in raw_comments]
    # Marker bytes deliberately have higher loss. Duplicate Unicode offsets
    # accumulate information without duplicating the byte denominator.
    losses = []
    density = []
    for index, char in enumerate(source):
        bits_per_byte = 9.0 if char == "/" else (3.0 if char == "-" else 1.0)
        density.append(bits_per_byte * (2.0 if char == "α" else 1.0))
        for _ in range(2 if char == "α" else 1):
            losses.append(TokenLoss(len(losses), index, index + 1,
                                    bits_per_byte * len(char.encode("utf-8")) * math.log(2.0)))
    values, occurrences = aggregate_content_groups(source, losses, spans, "cpp")
    assert [row["content_group"] for row in occurrences] == ["prose", "separator", "unknown"]
    total_bits = total_bytes = 0.0
    for group, span, raw, occurrence in zip(("prose", "separator", "unknown"), spans, raw_comments, occurrences):
        expected_bytes = len(raw.encode("utf-8"))
        expected_bits = sum(density[index] * len(source[index].encode("utf-8"))
                            for index in range(span.start, span.end))
        assert values[group + "__covered_bytes"] == expected_bytes
        assert values[group + "__bits"] == pytest.approx(expected_bits, abs=1e-10)
        assert values[PREFIX + group + "__bpb_mean"] == pytest.approx(expected_bits / expected_bytes)
        assert occurrence["raw_comment"] == raw
        assert occurrence["start"] == span.start and occurrence["end"] == span.end
        assert occurrence["covered_bytes"] == expected_bytes
        assert occurrence["bits"] == pytest.approx(expected_bits)
        total_bits += expected_bits
        total_bytes += expected_bytes
    assert values["all_comment_covered_bytes"] == total_bytes
    assert values["all_comment_bpb"] == pytest.approx(total_bits / total_bytes)
    assert sum(values[group + "__bits"] for group in GROUPS) == pytest.approx(total_bits)
    assert sum(values[group + "__covered_bytes"] for group in GROUPS) == total_bytes
    assert values[PREFIX + "prose__bpb_mean"] > 1.0
    assert np.isnan(values[PREFIX + "code_like__bpb_mean"])


def test_absent_groups_are_undefined_bpb_not_zero_difficulty():
    values, occurrences = aggregate_content_groups("x", [TokenLoss(0, 0, 1, math.log(2.0))], [], "cpp")
    assert occurrences == []
    assert values["all_comment_bpb"] is None
    assert values["all_comment_covered_bytes"] == 0
    for group in GROUPS:
        assert np.isnan(values[PREFIX + group + "__bpb_mean"])
        assert values[group + "__covered_bytes"] == 0
        assert values[group + "__bits"] == 0
        assert values[group + "__occurrence_count"] == 0


def test_cross_group_overlapping_original_spans_are_not_silently_called_partition():
    source = "/* Compute the sum for values. // ----- */"
    nested_start, nested_end = source.index("//"), source.index(" */")
    spans = [SimpleNamespace(start=0, end=len(source)),
             SimpleNamespace(start=nested_start, end=nested_end)]
    losses = [TokenLoss(index, index, index + 1, math.log(2.0)) for index in range(len(source))]
    with pytest.raises(ValueError, match="overlap"):
        aggregate_content_groups(source, losses, spans, "cpp")


@pytest.mark.parametrize("text,language,syntax_form", [
    ("//#define SVH(_R, _C) (svh[(_C)][(_R)])", "cuda", "line"),
    ("//#define SUM(x, y) ((x) + (y))", "cpp", "line"),
    ("//#define COUNT 12", "c", "line"),
    ("//#include <vector>", "cpp", "line"),
    ('//#include "local_header.h"', "c", "line"),
    ("//#pragma once", "cpp", "line"),
    ('//#define WARNING "Warning: // choose the count before starting."', "cpp", "line"),
    ('//#define WARNING R"(Warning: // choose the count before starting.)"', "cpp", "line"),
    ("/*\n#if defined(FEATURE)\nint count = 1;\n#endif\n*/", "cpp", "block"),
    ("/*\n#ifdef FEATURE\n#define COUNT 12\n#endif\n*/", "cpp", "block"),
    ("/*\n#ifndef FEATURE\n#define SUM(x, y) ((x) + (y))\n#endif\n*/", "cpp", "block"),
    ("/*\n#ifdef FEATURE\n#endif\n*/", "cpp", "block"),
    ("/*\n#ifndef FEATURE\n#endif\n*/", "cpp", "block"),
    ("/*\n#if FEATURE\n#endif\n*/", "cpp", "block"),
    ("/*\n#if FEATURE\n#define COUNT 1\n#elif OTHER\n#define COUNT 2\n#else\n#define COUNT 3\n#endif\n*/", "cpp", "block"),
])
def test_structurally_complete_preprocessor_code_including_actual_cuda_macro(text, language, syntax_form):
    classified = classify_comment_content(text, language, syntax_form)
    assert classified.group == "code_like", classified


@pytest.mark.parametrize("text", [
    "//#if FEATURE",
    "//#ifdef FEATURE",
    "//#ifndef FEATURE",
    "//#if",
    "//#endif",
    "//#else",
    "//#elif FEATURE",
    "//#this is prose()",
    "//#banana apple",
    "//#include the manual before reading",
    "/*\n#ifdef FEATURE\nint count = 1;\n*/",
])
def test_incomplete_or_nonoperational_preprocessor_like_text_is_not_code(text):
    classified = classify_comment_content(text, "cpp")
    assert classified.group != "code_like", classified


@pytest.mark.parametrize("text,expected", [
    ("// The SVH macro selects the requested matrix element.", "prose"),
    ("// Macro SVH(_R, _C) selects the requested matrix element.", "prose"),
    ("// Define SVH only after validating the matrix dimensions.", "prose"),
    ("// Read #define as the directive name in the documentation.", "prose"),
    ("// Choose the macro carefully; it controls the matrix access.", "prose"),
    ("// Use `#define LIMIT 10` only before compiling the program.", "mixed_unknown"),
    ("/*\n#define LIMIT 10\nSet the upper limit before allocating the buffer.\n*/", "mixed_unknown"),
    ("//#define COUNT 12 // Choose the count before starting.", "mixed_unknown"),
    ("//#define INC(x) ((x) + 1) /* Increment after validating the input. */", "mixed_unknown"),
    ('//#define WARNING "literal // text" // Explain this warning to the user.', "mixed_unknown"),
])
def test_macro_mentions_do_not_turn_descriptive_prose_into_standalone_code(text, expected):
    classified = classify_comment_content(text, "cpp")
    assert classified.group == expected, classified


@pytest.mark.parametrize("text", [
    '//#define WARNING "Warning: /* choose the count before starting. */"',
    '//#define WARNING R"tag(Warning: /* choose the count */ and // continue)tag"',
    '//#define WARNING R"(literal /* text */)" /* Explain this warning to the user. */',
    "//#define F(x, y",
    "//#define 12 invalid macro name",
])
def test_incomplete_or_parser_unsupported_macro_syntax_stays_explicitly_unknown_not_prose(text):
    # Valid quoted/raw-block macro values expose a tree-sitter preproc_arg
    # limitation. They must not be asserted natural prose, nor promoted to
    # supported code by reconstructing a different program for the parser.
    classified = classify_comment_content(text, "cpp")
    assert classified.group == "unknown", classified
    assert "macro" in classified.reason.lower()
    assert "unsupported" in classified.reason.lower() or "incomplete" in classified.reason.lower()
