from .types import MaskConstraints


DEFAULT_CONSTRAINTS = MaskConstraints(nmin=2, nmax=8, lmin=2, lmax=20)
DEFAULT_AST_MIN_TOKENS = 8
DEFAULT_AST_GRANULARITY = "control"
DEFAULT_AST_MAX_COMBINATION_SIZE = 3
DEFAULT_AST_MAX_SAMPLES_PER_STRATUM = None
DEFAULT_AST_SAMPLING_SEED = 42
